# Splunk Deployer Web Configuration
# Generated: 2025-08-23T21:17:58.374756

[settings]
enableSplunkWebSSL = false
startwebserver = 1
httpport = 8000
enableSplunkWeb = 1
login_content = Welcome to Splunk Deployer
appServerPorts = 8065
