# Splunk Search Head Authentication Configuration
# Generated: 2025-08-23T21:17:58.376041

[authentication]
authType = Splunk
authSettings = LDAP

[roleMap_Splunk]
admin = admin
power = power
user = user
