# Splunk Search Head Limits Configuration
# Generated: 2025-08-23T21:17:58.376383

[thruput]
maxKBps = 0

[search]
max_searches_per_cpu = 0

[realtime_search]
max_realtime_search_users = 0

[search_process]
max_search_processes = 0

[search_scheduler]
max_searches_per_cpu = 0

[search_artifacts]
max_search_artifacts = 0

[search_parser]
max_search_parser_errors = 0
