# Splunk Search Head Web Configuration
# Generated: 2025-08-23T21:17:58.376214

[settings]
enableSplunkWebSSL = false
startwebserver = 1
httpport = 8000
enableSplunkWeb = 1
login_content = Welcome to Splunk Search Head
appServerPorts = 8065
