# Splunk Deployment Server Server Class Configuration
# Generated: 2025-08-23T21:17:58.379262

[serverClass:universal_forwarders]
whitelist.0 = *
restartSplunkd = 1
targetWorkbookCacheSizeMB = 256

[serverClass:heavy_forwarders]
whitelist.0 = *
restartSplunkd = 1
targetWorkbookCacheSizeMB = 256

[serverClass:indexers]
whitelist.0 = *
restartSplunkd = 1
targetWorkbookCacheSizeMB = 256

[serverClass:search_heads]
whitelist.0 = *
restartSplunkd = 1
targetWorkbookCacheSizeMB = 256
