# Splunk Cluster Manager Authentication Configuration
# Generated: 2025-08-23T21:17:58.373176

[authentication]
authType = Splunk
authSettings = LDAP

[roleMap_Splunk]
admin = admin
power = power
user = user
