# Splunk Cluster Manager Authorization Configuration
# Generated: 2025-08-23T21:17:58.373003

[role_admin]
srchIndexesDefault = *
srchIndexesAllowed = *
srchMaxTime = 0
srchJobsQuota = 0
srchDiskQuota = 0
srchFilter = *
srchTimeWin = 0
srchTimeEarliest = 0
srchTimeLatest = 0
srchMaxCount = 0
srchMaxCountUnlimited = 1
srchMaxTimeUnlimited = 1
srchFilterUnlimited = 1
srchTimeWinUnlimited = 1
srchTimeEarliestUnlimited = 1
srchTimeLatestUnlimited = 1

[role_power]
srchIndexesDefault = main
srchIndexesAllowed = main, _internal, _audit
srchMaxTime = 0
srchJobsQuota = 0
srchDiskQuota = 0
srchFilter = *
srchTimeWin = 0
srchTimeEarliest = 0
srchTimeLatest = 0
srchMaxCount = 0
srchMaxCountUnlimited = 1
srchMaxTimeUnlimited = 1
srchFilterUnlimited = 1
srchTimeWinUnlimited = 1
srchTimeEarliestUnlimited = 1
srchTimeLatestUnlimited = 1

[role_user]
srchIndexesDefault = main
srchIndexesAllowed = main
srchMaxTime = 0
srchJobsQuota = 0
srchDiskQuota = 0
srchFilter = *
srchTimeWin = 0
srchTimeEarliest = 0
srchTimeLatest = 0
srchMaxCount = 0
srchMaxCountUnlimited = 1
srchMaxTimeUnlimited = 1
srchFilterUnlimited = 1
srchTimeWinUnlimited = 1
srchTimeEarliestUnlimited = 1
srchTimeLatestUnlimited = 1
