# Splunk Indexes Configuration for Cluster Manager
# Generated: 2025-08-23T21:17:58.372771

[default]
repFactor = 0
maxHotBuckets = 10
maxWarmDBCount = 300
maxTotalDataSizeMB = 500000
maxDataSize = auto_high_volume
homePath = $SPLUNK_DB/$_index_name/db
coldPath = $SPLUNK_DB/$_index_name/colddb
thawedPath = $SPLUNK_DB/$_index_name/thaweddb

[main]
repFactor = 0
homePath = $SPLUNK_DB/main/db
coldPath = $SPLUNK_DB/main/colddb
thawedPath = $SPLUNK_DB/main/thaweddb
maxDataSize = auto_high_volume

[_internal]
repFactor = 0
homePath = $SPLUNK_DB/_internal/db
coldPath = $SPLUNK_DB/_internal/colddb
thawedPath = $SPLUNK_DB/_internal/thaweddb
maxDataSize = 1000

[_audit]
repFactor = 0
homePath = $SPLUNK_DB/_audit/db
coldPath = $SPLUNK_DB/_audit/colddb
thawedPath = $SPLUNK_DB/_audit/thaweddb
maxDataSize = 1000

[security]
repFactor = 0
homePath = $SPLUNK_DB/security/db
coldPath = $SPLUNK_DB/security/colddb
thawedPath = $SPLUNK_DB/security/thaweddb
maxDataSize = auto_high_volume

[network]
repFactor = 0
homePath = $SPLUNK_DB/network/db
coldPath = $SPLUNK_DB/network/colddb
thawedPath = $SPLUNK_DB/network/thaweddb
maxDataSize = auto_high_volume

[infrastructure]
repFactor = 0
homePath = $SPLUNK_DB/infrastructure/db
coldPath = $SPLUNK_DB/infrastructure/colddb
thawedPath = $SPLUNK_DB/infrastructure/thaweddb
maxDataSize = auto_high_volume

[application]
repFactor = 0
homePath = $SPLUNK_DB/application/db
coldPath = $SPLUNK_DB/application/colddb
thawedPath = $SPLUNK_DB/application/thaweddb
maxDataSize = auto_high_volume
