# Splunk Monitoring Console Web Configuration
# Generated: 2025-08-23T21:17:58.384428

[settings]
enableSplunkWebSSL = false
startwebserver = 1
httpport = 8000
enableSplunkWeb = 1
login_content = Welcome to Splunk Monitoring Console
appServerPorts = 8065
