interface Task {
  name: string;
  module: string;
  parameters: Record<string, any>;
  when?: string;
  register?: string;
}

interface Job {
  id: string;
  name: string;
  targets: {
    server_class?: string;
    hosts?: string[];
    exclude_hosts?: string[];
  };
  execution_options: {
    remote_user: string;
    become?: boolean;
    become_user?: string;
    on_failure: 'stop' | 'continue' | 'rollback';
  };
  vars: Record<string, any>;
  tasks: Task[];
}

interface Playbook {
  automation_playbook: Job[];
}

export const generateYAML = (playbook: Playbook): string => {
  let yaml = '# Automation Playbook Generated by SIEMPLY\n';
  yaml += 'automation_playbook:\n\n';

  // Filter out jobs with no tasks
  const validJobs = playbook.automation_playbook.filter(job => job.tasks && job.tasks.length > 0);
  
  if (validJobs.length === 0) {
    yaml += '  # No valid jobs found\n';
    return yaml;
  }

  validJobs.forEach((job, jobIndex) => {
    yaml += `  - job:\n`;
    yaml += `      id: ${job.id || 'unnamed_job'}\n`;
    yaml += `      name: "${job.name || 'Unnamed Job'}"\n\n`;
    
    // Targets
    yaml += `      targets:\n`;
    if (job.targets.server_class && job.targets.server_class.trim()) {
      yaml += `        server_class: ${job.targets.server_class}\n`;
    }
    if (job.targets.hosts && job.targets.hosts.length > 0) {
      yaml += `        hosts:\n`;
      job.targets.hosts.forEach(host => {
        if (host && host.trim()) {
          yaml += `          - ${host}\n`;
        }
      });
    }
    if (job.targets.exclude_hosts && job.targets.exclude_hosts.length > 0) {
      yaml += `        exclude_hosts:\n`;
      job.targets.exclude_hosts.forEach(host => {
        if (host && host.trim()) {
          yaml += `          - ${host}\n`;
        }
      });
    }
    yaml += '\n';

    // Execution options
    yaml += `      execution_options:\n`;
    yaml += `        remote_user: ${job.execution_options.remote_user}\n`;
    if (job.execution_options.become) {
      yaml += `        become: yes\n`;
      if (job.execution_options.become_user) {
        yaml += `        become_user: ${job.execution_options.become_user}\n`;
      }
    }
    yaml += `        on_failure: ${job.execution_options.on_failure}\n\n`;

    // Variables
    if (Object.keys(job.vars).length > 0) {
      yaml += `      vars:\n`;
      Object.entries(job.vars).forEach(([key, value]) => {
        if (typeof value === 'string') {
          yaml += `        ${key}: "${value}"\n`;
        } else {
          yaml += `        ${key}: ${JSON.stringify(value)}\n`;
        }
      });
      yaml += '\n';
    }

    // Tasks
    yaml += `      tasks:\n`;
    job.tasks.forEach((task, taskIndex) => {
      yaml += `        - name: "${task.name || 'Unnamed Task'}"\n`;
      yaml += `          ${task.module}:\n`;
      
      // Module parameters
      Object.entries(task.parameters).forEach(([key, value]) => {
        if (value !== '' && value !== null && value !== undefined) {
          if (typeof value === 'string' && value.trim()) {
            yaml += `            ${key}: "${value}"\n`;
          } else if (typeof value === 'boolean') {
            yaml += `            ${key}: ${value ? 'yes' : 'no'}\n`;
          } else if (typeof value === 'number') {
            yaml += `            ${key}: ${value}\n`;
          } else if (typeof value === 'string' && !value.trim()) {
            // Skip empty strings
          }
        }
      });

      // Conditional execution
      if (task.when && task.when.trim()) {
        yaml += `          when: ${task.when}\n`;
      }

      // Register output
      if (task.register && task.register.trim()) {
        yaml += `          register: ${task.register}\n`;
      }

      if (taskIndex < job.tasks.length - 1) {
        yaml += '\n';
      }
    });

    if (jobIndex < playbook.automation_playbook.length - 1) {
      yaml += '\n';
    }
  });

  return yaml;
};

export const validatePlaybook = (playbook: Playbook): { isValid: boolean; errors: string[] } => {
  const errors: string[] = [];

  if (!playbook.automation_playbook || playbook.automation_playbook.length === 0) {
    errors.push('At least one job is required');
    return { isValid: false, errors };
  }

  // Filter out jobs with no tasks for validation
  const validJobs = playbook.automation_playbook.filter(job => job.tasks && job.tasks.length > 0);
  
  if (validJobs.length === 0) {
    errors.push('At least one job with tasks is required');
    return { isValid: false, errors };
  }

  validJobs.forEach((job, jobIndex) => {
    if (!job.id || job.id.trim() === '') {
      errors.push(`Job ${jobIndex + 1}: ID is required`);
    }

    if (!job.name || job.name.trim() === '') {
      errors.push(`Job ${jobIndex + 1}: Name is required`);
    }

    if (!job.execution_options.remote_user || job.execution_options.remote_user.trim() === '') {
      errors.push(`Job ${jobIndex + 1}: Remote user is required`);
    }

    job.tasks.forEach((task, taskIndex) => {
      if (!task.name || task.name.trim() === '') {
        errors.push(`Job ${jobIndex + 1}, Task ${taskIndex + 1}: Task name is required`);
      }

      if (!task.module || task.module.trim() === '') {
        errors.push(`Job ${jobIndex + 1}, Task ${taskIndex + 1}: Module is required`);
      }
    });
  });

  return {
    isValid: errors.length === 0,
    errors
  };
}; 